Prototypr\SystemBundle\Entity\Application:
  type: entity
  table: application
  repositoryClass: Prototypr\SystemBundle\Entity\ApplicationRepository
  fields:
    name:
      type: string
      unique: true
    routingPrefix:
      column: routing_prefix
      type: string
      unique: true
  oneToMany:
    pages:
      targetEntity: Prototypr\SystemBundle\Entity\Page
      mappedBy: application