Prototypr\SystemBundle\Entity\Base:
  type: mappedSuperclass
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    createdAt:
      column: created_at
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      column: updated_at
      type: datetime
      gedmo:
        timestampable:
          on: update
    ordering:
      type: integer
    active:
      type: boolean
      default: false