Prototypr\SystemBundle\Entity\Bundle:
  type: entity
  table: bundle
  repositoryClass: Prototypr\SystemBundle\Entity\BundleRepository
  fields:
    class:
      type: string
  manyToOne:
    application:
      fetch: EAGER
      targetEntity: Prototypr\SystemBundle\Entity\Application
      inversedBy: bundles
      joinColumn:
        name: application_id
        referencedColumnName: id
        onDelete: cascade