Prototypr\SystemBundle\Entity\Bundle:
  type: entity
  table: bundle
  repositoryClass: Prototypr\SystemBundle\Entity\BundleRepository
  fields:
    class:
      type: string
      unique: true
  oneToMany:
    pageBundles:
      targetEntity: Prototypr\SystemBundle\Entity\PageBundle
      mappedBy: bundle
  manyToOne:
    application:
      targetEntity: Prototypr\SystemBundle\Entity\Application
      inversedBy: bundles
      joinColumn:
        name: application_id
        referencedColumnName: id
        onDelete: cascade