Prototypr\SystemBundle\Entity\Node:
  type: mappedSuperclass
  fields:
    headers:
      type: string
      nullable: true
    title:
      type: string
      nullable: true
    slug:
      type: string
      length: 255
      nullable: true
      gedmo:
        slug:
          fields: [name]
          separator: -
    name:
      type: string