Prototypr\SystemBundle\Entity\Page:
  type: entity
  table: page
  repositoryClass: Prototypr\SystemBundle\Entity\PageRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    title:
      type: string
    active:
      type: boolean
    ordering:
      type: integer
    createdAt:
      column: created_at
      type: datetime
    updatedAt:
      column: updated_at
      type: datetime
  oneToMany:
    children:
      targetEntity: Prototypr\SystemBundle\Entity\Page
      mappedBy: parent
  manyToOne:
    parent:
      targetEntity: Prototypr\SystemBundle\Entity\Page
      inversedBy: children
      joinColumn:
        name: parent_id
        referencedColumnName: id
        onDelete: cascade
    application:
      fetch: EAGER
      targetEntity: Prototypr\SystemBundle\Entity\Application
      inversedBy: pages
      joinColumn:
        name: application_id
        referencedColumnName: id
        onDelete: cascade