Prototypr\SystemBundle\Entity\Page:
  type: entity
  table: page
  repositoryClass: Prototypr\SystemBundle\Entity\PageRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    title:
      type: string
      gedmo:
        - sluggable
    active:
      type: boolean
    ordering:
      type: integer
    slug:
      type: string
      length: 255
      nullable: true
      gedmo:
        slug:
          fields: [title]
          separator: -
    createdAt:
      column: created_at
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      column: updated_at
      type: datetime
      gedmo:
        timestampable:
          on: update
  oneToMany:
    children:
      targetEntity: Prototypr\SystemBundle\Entity\Page
      mappedBy: parent
  manyToOne:
    parent:
      targetEntity: Prototypr\SystemBundle\Entity\Page
      inversedBy: children
      joinColumn:
        name: parent_id
        referencedColumnName: id
        onDelete: cascade
    application:
      fetch: EAGER
      targetEntity: Prototypr\SystemBundle\Entity\Application
      inversedBy: pages
      joinColumn:
        name: application_id
        referencedColumnName: id
        onDelete: cascade