Prototypr\SystemBundle\Entity\PageBundle:
  type: entity
  table: page_bundle
  fields:
    master:
      type: boolean
      default: false
    bundle_application: # Used to override the application used in the bundle. Like mapping a frontend bundle to an intranet application.
      type: string
      nullable: true
  manyToOne:
    page:
      targetEntity: Prototypr\SystemBundle\Entity\Page
      inversedBy: pageBundles
      joinColumn:
        name: page_id
        referencedColumnName: id
        nullable: false
        onDelete: cascade
    bundle:
      targetEntity: Prototypr\SystemBundle\Entity\Bundle
      inversedBy: pageBundles
      joinColumn:
        name: bundle_id
        referencedColumnName: id
        nullable: false
        onDelete: cascade
    application:
      targetEntity: Prototypr\SystemBundle\Entity\Application
      inversedBy: pageBundles
      joinColumn:
        name: application_id
        referencedColumnName: id
        onDelete: cascade
        nullable: false