Prototypr\SystemBundle\Entity\PageBundle:
  type: entity
  table: page_bundle
  fields:
    master:
      type: boolean
      default: false
  manyToOne:
    page:
      targetEntity: Prototypr\SystemBundle\Entity\Page
      inversedBy: pageBundles
      joinColumn:
        name: page_id
        referencedColumnName: id
        nullable: false
        onDelete: cascade
    bundle:
      targetEntity: Prototypr\SystemBundle\Entity\Bundle
      inversedBy: pageBundles
      joinColumn:
        name: bundle_id
        referencedColumnName: id
        nullable: false
        onDelete: cascade