Prototypr\SystemBundle\Entity\Page:
  type: entity
  table: page
  repositoryClass: Prototypr\SystemBundle\Entity\PageRepository
  oneToMany:
    children:
      targetEntity: Prototypr\SystemBundle\Entity\Page
      mappedBy: parent
    pageBundles:
      targetEntity: Prototypr\SystemBundle\Entity\PageBundle
      mappedBy: page
  manyToOne:
    parent:
      targetEntity: Prototypr\SystemBundle\Entity\Page
      inversedBy: children
      joinColumn:
        name: parent_id
        referencedColumnName: id
        onDelete: cascade
    application:
      fetch: EAGER
      targetEntity: Prototypr\SystemBundle\Entity\Application
      inversedBy: pages
      joinColumn:
        name: application_id
        referencedColumnName: id
        onDelete: cascade
        nullable: false