system_login:
    pattern:   /user/login/{application}
    defaults:  { _controller: PrototyprSystemBundle:Security:login, application: ~ }

system_login_check:
    pattern:   /user/login_check

system_logout:
    pattern:   /user/logout
