parameters:

    prototypr.system.kernel.class: Prototypr\SystemBundle\Core\SystemKernel
    prototypr.system.controller_listener.class: Prototypr\SystemBundle\Listener\ControllerListener
    prototypr.system.pre_persist_listener.class: Prototypr\SystemBundle\Listener\PrePersistListener
    prototypr.system.router_loader.class: Prototypr\SystemBundle\Router\SystemLoader
    prototypr.system.router_cache.class: Prototypr\SystemBundle\Router\Cache
    prototypr.system.twig_utility_extension.class: Prototypr\SystemBundle\Twig\UtilityExtension
    prototypr.system.twig_routing_extension.class: Prototypr\SystemBundle\Twig\RoutingExtension
    prototypr.system.route_map.bundle.class: Prototypr\SystemBundle\EntityRouteMap\BundleMap

services:

    prototypr.system.kernel:
        class: %prototypr.system.kernel.class%
        shared: true
        calls:
          - [ setLogger, [ @logger ] ]

    prototypr.system.controller_listener:
        class: %prototypr.system.controller_listener.class%
        tags:
          - { name: kernel.event_listener, event: kernel.controller }
        arguments: [ @prototypr.system.kernel, @service_container ]
        calls:
          - [ setLogger, [ @logger ] ]

    prototypr.system.pre_persist_listener:
        class: %prototypr.system.pre_persist_listener.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    prototypr.system.router_cache:
        class: %prototypr.system.router_cache.class%
        arguments: [ @kernel ]

    prototypr.system.twig_utility_extension:
        class: %prototypr.system.twig_utility_extension.class%
        arguments: [ @prototypr.system.kernel ]
        tags:
            - { name: twig.extension }

    prototypr.system.twig_routing_extension:
        class: %prototypr.system.twig_routing_extension.class%
        arguments: [ @router, @service_container ]
        tags:
            - { name: twig.extension }

    prototypr_system.route_map.bundle:
        class: %prototypr.system.route_map.bundle.class%
        calls:
          - [ setSystemKernel, [ @prototypr.system.kernel ] ]
          - [ setRouter, [ @router ] ]


