parameters:

    prototypr.system.kernel.class: Prototypr\SystemBundle\Core\SystemKernel
    prototypr.system.controller_listener.class: Prototypr\SystemBundle\Listener\ControllerListener
    prototypr.system.pre_persist_listener.class: Prototypr\SystemBundle\Listener\PrePersistListener
    prototypr.system.router_loader.class: Prototypr\SystemBundle\Router\SystemLoader
    prototypr.system.router_cache.class: Prototypr\SystemBundle\Router\Cache
    prototypr.system.twig_extension.class: Prototypr\SystemBundle\Twig\Extension\

services:

    prototypr.system.kernel:
        class: %prototypr.system.kernel.class%
        shared: true
        calls:
          - [ setLogger, [ @logger ] ]

    prototypr.system.controller_listener:
        class: %prototypr.system.controller_listener.class%
        tags:
          - { name: kernel.event_listener, event: kernel.controller }
        arguments:
          - [ @prototypr.system.kernel ]
          - [ @service_container ]
        calls:
          - [ setLogger, [ @logger ] ]

    prototypr.system.pre_persist_listener:
        class: %prototypr.system.pre_persist_listener.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    prototypr.system.router_cache:
        class: %prototypr.system.router_cache.class%
        arguments:
          - [ @kernel ]

    prototypr.system.twig_extension:
        class: %prototypr.system.twig_extension.class%
        arguments:
          - [ @request ]
        tags:
            - { name: twig.extension }


