<?php

namespace Prototypr\SystemBundle\Entity;

use Prototypr\SystemBundle\Core\BaseEntityRepository;

/**
 * BundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BundleRepository extends BaseEntityRepository
{
}