<?php

namespace Prototypr\SystemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTagRepository extends EntityRepository
{
}