<?php

namespace Prototypr\SystemBundle\Entity;

use Prototypr\SystemBundle\Core\BaseEntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends BaseEntityRepository
{
}